name: Build

on:
  push:
    branches:
      - forserino
      - "bugfix-release/*"
      - "release/*"
  pull_request:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: true
        type: choice
        default: "auto"
        options:
          - auto
          - nightly
          - stable
  merge_group:

permissions:
  contents: write
  actions: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  C2_ENABLE_LTO: ${{ github.ref == 'refs/heads/forserino' || startsWith(github.ref, 'refs/heads/bugfix-release/') || startsWith(github.ref, 'refs/heads/release/') }}
  CHATTERINO_REQUIRE_CLEAN_GIT: On
  CHATTERINO_BUILD_TYPE: ${{ github.event.inputs.buildType || 'auto' }}
  CONAN_VERSION: 2.11.0

jobs:
  build-ubuntu-docker:
    name: "Build Ubuntu in Docker"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            container: ghcr.io/chatterino/chatterino2-build-ubuntu-22.04:latest
            qt-version: 6.7.2
            force-lto: false
            skip-artifact: false
            skip-crashpad: false
            build-deb: true
            plugins: true
          - os: ubuntu-24.04
            container: ghcr.io/chatterino/chatterino2-build-ubuntu-24.04:latest
            qt-version: 6.7.2
            force-lto: false
            skip-artifact: false
            skip-crashpad: false
            build-deb: true
            plugins: true
          - os: ubuntu-24.04
            container: ghcr.io/chatterino/chatterino2-build-ubuntu-24.04:latest
            qt-version: 6.7.2
            force-lto: false
            skip-artifact: false
            skip-crashpad: false
            build-deb: false
            plugins: false
    env:
      C2_ENABLE_LTO: ${{ matrix.force-lto }}
      C2_ENABLE_CRASHPAD: ${{ matrix.skip-crashpad == false }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fix git permission error
        run: |
          git config --global --add safe.directory '*'

      - name: Determine build type
        id: build-type
        shell: bash
        run: |
          if [ "${CHATTERINO_BUILD_TYPE}" = "auto" ]; then
            if git describe --exact-match --match 'v*'; then
              echo "NIGHTLY_BUILD=Off" >> "$GITHUB_OUTPUT"
            else
              echo "NIGHTLY_BUILD=On" >> "$GITHUB_OUTPUT"
            fi
          elif [ "${CHATTERINO_BUILD_TYPE}" = "nightly" ]; then
            echo "NIGHTLY_BUILD=On" >> "$GITHUB_OUTPUT"
          elif [ "${CHATTERINO_BUILD_TYPE}" = "stable" ]; then
            echo "NIGHTLY_BUILD=Off" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi

      - name: Install Python and libclang (24.04)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt -y --no-install-recommends install \
            python3 python3-venv clang-18 clang-format-18 libclang-18-dev
          echo "LIBCLANG_LIBRARY_FILE=/usr/lib/x86_64-linux-gnu/libclang-18.so" >> "$GITHUB_ENV"
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 42
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 42

      - name: Build
        run: |
          mkdir build
          cd build
          CXXFLAGS=-fno-sized-deallocation cmake \
            -DCMAKE_INSTALL_PREFIX=appdir/usr/ \
            -DCMAKE_BUILD_TYPE=Release \
            -DPAJLADA_SETTINGS_USE_BOOST_FILESYSTEM=On \
            -DUSE_PRECOMPILED_HEADERS=OFF \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
            -DCHATTERINO_LTO="$C2_ENABLE_LTO" \
            -DCMAKE_PREFIX_PATH="$Qt6_DIR/lib/cmake" \
            -DCHATTERINO_STATIC_QT_BUILD=On \
            -DCHATTERINO_NIGHTLY_BUILD=${{ steps.build-type.outputs.NIGHTLY_BUILD }} \
            -DFORCE_JSON_GENERATION=${{matrix.os == 'ubuntu-24.04' && 'On' || 'Off'}} \
            -DCHATTERINO_PLUGINS=${{ matrix.plugins && 'On' || 'Off' }} \
            ..
          make -j"$(nproc)"

      - name: Check generated sources
        if: matrix.os == 'ubuntu-24.04'
        run: |
          git add -N lib/twitch-eventsub-ws/include lib/twitch-eventsub-ws/src
          git --no-pager diff --exit-code lib/twitch-eventsub-ws/include lib/twitch-eventsub-ws/src

      - name: Package - .deb (Ubuntu)
        if: matrix.build-deb
        run: |
          cd build
          sh ./../.CI/CreateUbuntuDeb.sh

      - name: Upload artifact - .deb (Ubuntu)
        if: matrix.build-deb
        uses: actions/upload-artifact@v4
        with:
          name: Chatterino-${{ matrix.os }}-Qt-${{ matrix.qt-version }}.deb
          path: build/Chatterino-${{ matrix.os }}-x86_64.deb

  build:
    name: "Build ${{ matrix.os }}, Qt ${{ matrix.qt-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            qt-version: 5.15.2
            force-lto: false
            plugins: true
            skip-artifact: false
            skip-crashpad: false
          - os: macos-14
            qt-version: 6.7.1
            force-lto: false
            skip-artifact: false
            skip-crashpad: false
          - os: windows-latest
            qt-version: 6.7.1
            force-lto: false
            skip-artifact: false
            skip-crashpad: false
      fail-fast: false
    env:
      C2_ENABLE_LTO: ${{ matrix.force-lto }}
      C2_ENABLE_CRASHPAD: ${{ matrix.skip-crashpad == false }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Determine build type
        id: build-type
        shell: bash
        run: |
          if [ "${CHATTERINO_BUILD_TYPE}" = "auto" ]; then
            if git describe --exact-match --match 'v*'; then
              echo "NIGHTLY_BUILD=Off" >> "$GITHUB_OUTPUT"
            else
              echo "NIGHTLY_BUILD=On" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "NIGHTLY_BUILD=${{ CHATTERINO_BUILD_TYPE == 'nightly' && 'On' || 'Off' }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.qt-version }}

      - name: Enable Developer Command Prompt (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Conan (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          pip3 install "conan==${{ env.CONAN_VERSION }}"
          conan profile detect -f

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          mkdir build; cd build
          conan install .. -s build_type=RelWithDebInfo --build=missing
          cmake .. -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCHATTERINO_NIGHTLY_BUILD="${{ steps.build-type.outputs.NIGHTLY_BUILD }}"
          nmake

      - name: Package (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          cd build
          7z a chatterino-windows-x86-64-Qt-${{ matrix.qt-version }}.zip bin/

      - name: Upload artifact (Windows)
        if: startsWith(matrix.os, 'windows') && !matrix.skip-artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatterino-windows-x86-64-Qt-${{ matrix.qt-version }}.zip
          path: build/*.zip

      - name: Build (MacOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir build; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCHATTERINO_NIGHTLY_BUILD=${{ steps.build-type.outputs.NIGHTLY_BUILD }}
          make -j$(sysctl -n hw.logicalcpu)

      - name: Upload artifact (MacOS)
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
          path: build/*.dmg

  create-release:
    needs: [build-ubuntu-docker, build]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/forserino')
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts/
          merge-multiple: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifacts: "release-artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Forserino Nightly
          tag: nightly-build
          prerelease: true

      - name: Update nightly-build tag
        run: |
          git tag -f nightly-build
          git push -f origin nightly-build